package go_openrpc_reflect

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"net/url"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"strings"

	go_jsonschema_walk "github.com/etclabscore/go-jsonschema-walk"
	"github.com/go-openapi/spec"
	"github.com/invopop/jsonschema"
	meta_schema "github.com/open-rpc/meta-schema"
)

var errType = reflect.TypeOf((*error)(nil)).Elem()
var errAutogenerated = errors.New("autogenerated file")
var errInvalidFilepath = errors.New("invalid filepath")

var nullContentDescriptor meta_schema.ContentDescriptorObject
var nullSchema meta_schema.JSONSchema

func init() {
	nullS := "Null"

	var nullT meta_schema.SimpleTypes = "null"

	required, deprecated := true, false

	nullSchema = meta_schema.JSONSchema{
		JSONSchemaObject: &meta_schema.JSONSchemaObject{
			Type: &meta_schema.Type{
				SimpleTypes: &nullT,
			},
		}}

	nullContentDescriptor = meta_schema.ContentDescriptorObject{
		Name:        (*meta_schema.ContentDescriptorObjectName)(&nullS),
		Description: (*meta_schema.ContentDescriptorObjectDescription)(&nullS),
		Schema:      &nullSchema,
		Required:    (*meta_schema.ContentDescriptorObjectRequired)(&required),
		Deprecated:  (*meta_schema.ContentDescriptorObjectDeprecated)(&deprecated),
	}
}

func receiverMethods(methodHandler MethodRegisterer, name string, receiver interface{}) (object []meta_schema.MethodOrReference, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("receiverMethods error: %w", err)
		}
	}()

	ty := reflect.TypeOf(receiver)
	rval := reflect.ValueOf(receiver)

	methods := meta_schema.Methods{}
	for m := 0; m < ty.NumMethod(); m++ {
		method := ty.Method(m)
		if !methodHandler.IsMethodEligible(method) {
			continue
		}

		fdecl, err := getAstFuncDecl(rval, method)
		if err != nil {
			if err == errAutogenerated {
				continue
			}
			// if err == errInvalidFilepath {
			// 	rval = reflect.ValueOf(rval.Type())
			// 	fdecl, err = getAstFuncDecl(rval, method)
			// 	if err != nil {
			// 		return nil, fmt.Errorf("getAstFuncDecl2 error: %w", err)
			// 	}
			// }
			return nil, fmt.Errorf("getAstFuncDecl error: %w, receiver: %v", err, ty.String())
		}

		name, err := methodHandler.GetMethodName(name, rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		description, err := methodHandler.GetMethodDescription(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		summary, err := methodHandler.GetMethodSummary(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		tags, err := methodHandler.GetMethodTags(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		paramsStructure, err := methodHandler.GetMethodParamStructure(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		params := []meta_schema.ContentDescriptorOrReference{}
		paramCDs, err := methodHandler.GetMethodParams(rval, method, fdecl)
		if err != nil {
			return nil, err
		}
		for i := range paramCDs {
			cp := paramCDs[i]
			params = append(params, meta_schema.ContentDescriptorOrReference{
				ContentDescriptorObject: &cp,
			})
		}

		resultCD, err := methodHandler.GetMethodResult(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		methodErrors, err := methodHandler.GetMethodErrors(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		links, err := methodHandler.GetMethodLinks(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		examples, err := methodHandler.GetMethodExamples(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		deprecated, err := methodHandler.GetMethodDeprecated(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		exDocs, err := methodHandler.GetMethodExternalDocs(rval, method, fdecl)
		if err != nil {
			return nil, err
		}

		me := meta_schema.MethodObject{
			Name:           (*meta_schema.MethodObjectName)(&name),
			Description:    (*meta_schema.MethodObjectDescription)(&description),
			Summary:        (*meta_schema.MethodObjectSummary)(&summary),
			Tags:           tags,
			ParamStructure: (*meta_schema.MethodObjectParamStructure)(&paramsStructure),
			Params:         (*meta_schema.MethodObjectParams)(&params),
			Result:         &meta_schema.MethodObjectResult{ContentDescriptorObject: &resultCD},
			Errors:         methodErrors,
			Links:          links,
			Examples:       examples,
			Deprecated:     (*meta_schema.MethodObjectDeprecated)(&deprecated),
			ExternalDocs:   exDocs,
		}
		methods = append(methods, meta_schema.MethodOrReference{MethodObject: &me})
	}
	return methods, nil
}

func buildContentDescriptorObject(registerer ContentDescriptorRegisterer, r reflect.Value, m reflect.Method, field *ast.Field, ty reflect.Type) (cd meta_schema.ContentDescriptorObject, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("build content descriptor error: %w", err)
		}
	}()

	name, err := registerer.GetContentDescriptorName(r, m, field)
	if err != nil {
		return cd, err
	}

	description, err := registerer.GetContentDescriptorDescription(r, m, field)
	if err != nil {
		return cd, err
	}

	summary, err := registerer.GetContentDescriptorSummary(r, m, field)
	if err != nil {
		return cd, err
	}

	required, err := registerer.GetContentDescriptorRequired(r, m, field)
	if err != nil {
		return cd, err
	}

	deprecated, err := registerer.GetContentDescriptorDeprecated(r, m, field)
	if err != nil {
		return cd, err
	}

	schema, err := registerer.GetSchema(r, m, field, ty)
	if err != nil {
		return cd, err
	}

	// // If name == description, eg. 'hexutil.Bytes' == 'hexutil.Bytes',
	// // that means the field represent an unnamed variable. Mostly likely an unnamed return value.
	// // Assigning a content descriptor name as a Go type name may be undesirable,
	// // particularly since the 'name' field is used in by-name paramStructure cases to key
	// // the parameter object.
	// // So instead of using this default, let's set the name value to be something
	// // generic given the context of the schema instead.
	// //
	// if name == description {
	//	// Field is unnamed.
	//	if schema.Title != nil {
	//		name = (string)(*schema.Title)
	//	} else if schema.Type != nil {
	//		if schema.Type.UnorderedSetOfAny17L18NF5VWcS9ROi != nil {
	//			u := schema.Type.UnorderedSetOfAny17L18NF5VWcS9ROi
	//			uu := *u
	//			a := uu[0]
	//			n, ok := a.(string)
	//			if !ok {
	//				panic("notok1")
	//			}
	//			name = n
	//		} else if schema.Type.Any17L18NF5 != nil {
	//			a := schema.Type.Any17L18NF5
	//			aa := *a
	//			n, ok := aa.(string)
	//			if !ok {
	//				panic("notok2")
	//			}
	//			name = n
	//		}
	//	}
	// }

	cd = meta_schema.ContentDescriptorObject{
		Name:        (*meta_schema.ContentDescriptorObjectName)(&name),
		Description: (*meta_schema.ContentDescriptorObjectDescription)(&description),
		Summary:     (*meta_schema.ContentDescriptorObjectSummary)(&summary),
		Schema:      &schema,
		Required:    (*meta_schema.ContentDescriptorObjectRequired)(&required),
		Deprecated:  (*meta_schema.ContentDescriptorObjectDeprecated)(&deprecated),
	}
	return
}

func buildJSONSchemaObject(registerer SchemaRegisterer, r reflect.Value, m reflect.Method, field *ast.Field, ty reflect.Type) (schema meta_schema.JSONSchema, err error) {
	// Initialize schema with empty object
	schema.JSONSchemaObject = &meta_schema.JSONSchemaObject{}

	if ty == nil {
		// Return a null type schema for nil types
		nullType := meta_schema.SimpleTypes("null")
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: &nullType,
		}
		return
	}

	// Handle pointer types first
	originalType := ty
	for ty.Kind() == reflect.Ptr {
		// Handle special cases
		if ty.Elem().Name() == "Int" && ty.Elem().PkgPath() == "math/big" {
			schema.JSONSchemaObject.Type = &meta_schema.Type{
				SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
			}
			// Set additionalProperties to false for big.Int
			falseVal := meta_schema.JSONSchemaBoolean(false)
			schema.JSONSchemaObject.AdditionalProperties = &meta_schema.JSONSchema{JSONSchemaBoolean: &falseVal}
			return
		}
		// Handle nil pointer
		if ty.Elem() == nil {
			schema.JSONSchemaObject.Type = &meta_schema.Type{
				SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("null")),
			}
			return
		}
		ty = ty.Elem()
	}

	// Handle special types that might cause reflection issues
	switch {
	case ty.Kind() == reflect.Interface:
		fallthrough
	case ty.Kind() == reflect.Ptr && ty.Elem().Kind() == reflect.Interface:
		fallthrough
	case !jsonschemaPkgSupport(ty):
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
		}
		// Set additionalProperties to false for object types
		falseVal := meta_schema.JSONSchemaBoolean(false)
		schema.JSONSchemaObject.AdditionalProperties = &meta_schema.JSONSchema{JSONSchemaBoolean: &falseVal}
		return
	}

	// Handle basic types directly
	switch ty.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("integer")),
		}
		return
	case reflect.Float32, reflect.Float64:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("number")),
		}
		return
	case reflect.Bool:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("boolean")),
		}
		return
	case reflect.String:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("string")),
		}
		return
	case reflect.Map:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
		}
		// Set additionalProperties to false for maps
		falseVal := meta_schema.JSONSchemaBoolean(false)
		schema.JSONSchemaObject.AdditionalProperties = &meta_schema.JSONSchema{JSONSchemaBoolean: &falseVal}
		return
	case reflect.Slice, reflect.Array:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("array")),
		}
		// Handle array item type
		if ty.Elem() != nil {
			itemSchema, err := buildJSONSchemaObject(registerer, r, m, field, ty.Elem())
			if err == nil && itemSchema.JSONSchemaObject != nil {
				// Create a reference to the item schema
				schema.JSONSchemaObject.Items = &meta_schema.Items{
					JSONSchema: &itemSchema,
				}
			}
		}
		return
	case reflect.Struct:
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
		}

		// Initialize properties
		properties := meta_schema.Properties{}
		schema.JSONSchemaObject.Properties = &properties

		// Set additionalProperties to false
		falseVal := meta_schema.JSONSchemaBoolean(false)
		schema.JSONSchemaObject.AdditionalProperties = &meta_schema.JSONSchema{JSONSchemaBoolean: &falseVal}

		// Add properties for struct fields
		for i := 0; i < ty.NumField(); i++ {
			field := ty.Field(i)
			if !field.IsExported() {
				continue
			}

			// Get the JSON tag name if present, otherwise use field name
			jsonName := field.Name
			if tag := field.Tag.Get("json"); tag != "" {
				if comma := strings.Index(tag, ","); comma != -1 {
					jsonName = tag[:comma]
				} else {
					jsonName = tag
				}
			}

			// Skip if json tag is "-"
			if jsonName == "-" {
				continue
			}

			fieldSchema, err := buildJSONSchemaObject(registerer, r, m, nil, field.Type)
			if err != nil {
				continue
			}

			// Handle required fields based on json tag
			if strings.Contains(field.Tag.Get("json"), ",required") {
				if schema.JSONSchemaObject.Required == nil {
					schema.JSONSchemaObject.Required = &meta_schema.StringArray{}
				}
				*schema.JSONSchemaObject.Required = append(*schema.JSONSchemaObject.Required, meta_schema.StringDoaGddGA(jsonName))
			}

			(*schema.JSONSchemaObject.Properties)[jsonName] = fieldSchema
		}
		return
	}

	// Create reflector with custom type handling
	rflctr := &jsonschema.Reflector{
		AllowAdditionalProperties:  false,
		RequiredFromJSONSchemaTags: true,
		ExpandedStruct:             true,
		IgnoredTypes:               registerer.SchemaIgnoredTypes(),
		Mapper:                     registerer.SchemaTypeMap(),
	}

	// Use the original type for reflection if it's a named pointer type
	reflectType := ty
	if originalType.Kind() == reflect.Ptr && originalType.Elem().Name() != "" {
		reflectType = originalType
	}

	// Protect against nil or invalid types
	if reflectType == nil || reflectType.Kind() == reflect.Invalid {
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
		}
		return
	}

	// Reflect the schema from the type
	var jsch *jsonschema.Schema
	defer func() {
		if r := recover(); r != nil {
			schema.JSONSchemaObject.Type = &meta_schema.Type{
				SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
			}
			err = nil
		}
	}()
	jsch = rflctr.ReflectFromType(reflectType)

	if jsch == nil {
		schema.JSONSchemaObject.Type = &meta_schema.Type{
			SimpleTypes: (*meta_schema.SimpleTypes)(stringPtr("object")),
		}
		return
	}

	// Convert to JSON for transformation
	mm, err := json.Marshal(jsch)
	if err != nil {
		return schema, fmt.Errorf("marshal schema error: %w", err)
	}

	// Unmarshal into our schema type
	err = json.Unmarshal(mm, &schema)
	if err != nil {
		return schema, fmt.Errorf("unmarshal schema error: %v\n\nschema JSON: %s", err, string(mm))
	}

	// Apply any schema mutations
	if mutations := registerer.SchemaMutations(reflectType); len(mutations) > 0 {
		// Create a new spec.Schema for mutations
		jj := &spec.Schema{}
		err = json.Unmarshal(mm, jj)
		if err != nil {
			return schema, fmt.Errorf("unmarshal to spec.Schema error: %w", err)
		}

		// Create a copy for definitions
		root := &spec.Schema{}
		if err := json.Unmarshal(mm, root); err != nil {
			return schema, fmt.Errorf("unmarshal root schema error: %w", err)
		}

		a := go_jsonschema_walk.NewWalker()
		for _, m := range mutations {
			mutFn := m(root)
			if err := a.DepthFirst(jj, mutFn); err != nil {
				return schema, fmt.Errorf("schema mutation error: %w", err)
			}
		}

		// Marshal the mutated schema
		out, err := json.Marshal(jj)
		if err != nil {
			return schema, fmt.Errorf("marshal mutated schema error: %w", err)
		}

		// Reinitialize and unmarshal the final schema
		schema = meta_schema.JSONSchema{JSONSchemaObject: &meta_schema.JSONSchemaObject{}}
		err = json.Unmarshal(out, &schema)
		if err != nil {
			return schema, fmt.Errorf("unmarshal mutated schema error: %v\nschema JSON: %s", err, string(out))
		}
	}

	// Add examples if available
	examples, err := registerer.SchemaExamples(reflectType)
	if err != nil {
		return schema, fmt.Errorf("get schema examples error: %w", err)
	}
	if schema.JSONSchemaObject != nil {
		schema.JSONSchemaObject.Examples = examples
	}

	return schema, nil
}

// Helper function to create string pointers
func stringPtr(s string) *string {
	return &s
}

func isExportedMethod(method reflect.Method) bool {
	return method.PkgPath == ""
}

func isExportedOrBuiltinType(t reflect.Type) bool {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	// PkgPath will be non-empty even for an exported type,
	// so we need to check the type name as well.
	return token.IsExported(t.Name()) || t.PkgPath() == ""
}

func getAstFuncDecl(r reflect.Value, m reflect.Method) (*ast.FuncDecl, error) {
	runtimeFunc := runtime.FuncForPC(m.Func.Pointer())
	runtimeFile, _ := runtimeFunc.FileLine(runtimeFunc.Entry())

	if strings.Contains(runtimeFile, "autogenerated") {
		return nil, errAutogenerated
	}

	tokenFileSet := token.NewFileSet()
	if !filepath.IsAbs(runtimeFile) {
		return nil, fmt.Errorf("%w: %s", errInvalidFilepath, runtimeFile)
	}

	astFile, err := parser.ParseFile(tokenFileSet, runtimeFile, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse file: %w, method: %s, file: %s", err, m.Name, runtimeFile)
	}

	rfName := runtimeFuncBaseName(runtimeFunc)

	for _, decl := range astFile.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Name == nil || fn.Name.Name != rfName {
			continue
		}

		fnRecName := ""
		if fn.Recv != nil && fn.Recv.List != nil && len(fn.Recv.List) > 0 {
			for _, l := range fn.Recv.List {
				if fnRecName != "" {
					break
				}

				i, ok := l.Type.(*ast.Ident)
				if ok {
					fnRecName = i.Name
					continue
				}
				s, ok := l.Type.(*ast.StarExpr)
				if ok {
					fnRecName = fmt.Sprintf("%v", s.X)
				}
			}
		}

		// Ensure that the receiver name matches.
		reRec := regexp.MustCompile(fnRecName + `\s`)
		if !reRec.MatchString(r.String()) {
			continue
		}
		return fn, nil
	}
	return nil, nil
}

func runtimeFuncBaseName(rf *runtime.Func) string {
	spl := strings.Split(rf.Name(), ".")
	return spl[len(spl)-1]
}

func githubLinkFromValue(receiver reflect.Value, runtimeF *runtime.Func) (*url.URL, error) {
	ty := receiver.Type()
	switch ty.Kind() {
	case reflect.Ptr, reflect.Interface:
		ty = ty.Elem()
	}
	packagePath := ty.PkgPath()

	if !strings.HasPrefix(packagePath, "github.com") {
		return nil, fmt.Errorf("'%s': not a github.com package name", packagePath)
	}

	uris := strings.Split(packagePath, "/") // eg. github.com / ethereum / go-ethereum / internal / ethapi / api.go | [.(*MyRec)... ]
	githubURIOwnerName := strings.Join(uris[:3], "/")
	githubURIRevision := "blob/master"
	pkgRelDir := ""
	pkgRelDir = strings.Join(uris[3:], "/")
	if pkgRelDir != "" {
		// Otherwise we get a double // for files at the module root.
		pkgRelDir = "/" + pkgRelDir
	}

	runtimeFile, runtimeLine := runtimeF.FileLine(runtimeF.Entry())
	base := filepath.Base(runtimeFile)

	ref := fmt.Sprintf("https://%s/%s%s/%s#L%d", githubURIOwnerName, githubURIRevision, pkgRelDir, base, runtimeLine)

	return url.Parse(ref)
}

func expandedFieldNamesFromList(in []*ast.Field) (out []*ast.Field) {
	expandedFields := []*ast.Field{}
	for _, f := range in {
		expandedFields = append(expandedFields, fieldsWithNames(f)...)
	}
	return expandedFields
}

// fieldsWithNames expands a field (either parameter or result, in this case) to
// fields which all have at least one name, or at least one field with one name.
// This handles unnamed fields, and fields declared using multiple names with one type.
// Unnamed fields are assigned a name that is the 'printed' identity of the field Type,
// eg. int -> int, bool -> bool
func fieldsWithNames(f *ast.Field) (fields []*ast.Field) {
	if f == nil {
		return nil
	}

	if len(f.Names) == 0 {
		fields = append(fields, &ast.Field{
			Doc:     f.Doc,
			Names:   []*ast.Ident{{Name: printIdentField(f)}},
			Type:    f.Type,
			Tag:     f.Tag,
			Comment: f.Comment,
		})
		return
	}
	for _, ident := range f.Names {
		fields = append(fields, &ast.Field{
			Doc:     f.Doc,
			Names:   []*ast.Ident{ident},
			Type:    f.Type,
			Tag:     f.Tag,
			Comment: f.Comment,
		})
	}
	return
}

func printIdentField(f *ast.Field) string {
	b := []byte{}
	buf := bytes.NewBuffer(b)
	fs := token.NewFileSet()
	printer.Fprint(buf, fs, f.Type.(ast.Node))
	return buf.String()
}

func jsonschemaPkgSupport(r reflect.Type) bool {
	rr := r
	if rr.Kind() == reflect.Ptr {
		rr = rr.Elem()
	}
	switch rr.Kind() {
	case reflect.Struct,
		reflect.Map,
		reflect.Slice, reflect.Array,
		reflect.Interface,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64,
		reflect.Bool,
		reflect.String,
		reflect.Ptr:
		// reflect.Chan:
		return true
	default:
		return false
	}
}
